<div class="static-page-description">
    <p>
        <?= __('No need to struggle with painful feet! Use the locator tool below to find a foot health professional in your area to help keep your feet healthy and in great condition.No need to struggle with painful feet! Use the locator tool below to find a foot health professional in your area to help keep your feet healthy and in great condition.') ?>
    </p>
    <p>
        <?= __('Please note: Inclusion on this locator does not confirm or imply any specific health qualification. Please contact practitioners directly for details of their professional qualifications.') ?>
    </p>
</div>
