<?php
$detailsArr = $block->getTransactiondetail();
$mhelper = $block->getHelperMagento();
// echo "<pre>";
// print_r($detailsArr);
// die;
//echo count($detailsArr);

//if (!empty($detailsArr)) {
if (!empty($detailsArr['allDetail']))
{
  $alldata=$detailsArr['allDetail'];
    ?>

       <div class="">
         <div class="page-title-wrapper">
        <!-- <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper"><?php //echo $alldata['attributes']['type']?></span>    </h1> -->
            <?php
      if(!empty($alldata)){
        // if($alldata['attributes']['currencyCode']=='GBP'){
        //   $currencycode='£';
        // }else if($alldata['attributes']['currencyCode']=='USD'){
        //   $currencycode='$';
        // }else if($alldata['attributes']['currencyCode']=='EURO'){
        //   $currencycode='€';
        // }else{
        //   $currencycode='';
        // }
        $currencycode='£';
        ?>
          <span class="base" style="font-size:16px;"><?php echo date('d/m/Y', strtotime($alldata['attributes']['date'])); ?></span>, <span style="font-size:16px;"><?php echo $alldata['attributes']['status']?></span>,
          <!-- <span class="order-status">Document # <?php //echo $alldata['attributes']['rootDocumentCode']; ?></span><br> -->
          <span class="base" style="font-size:16px;"><?php echo $alldata['attributes']['type']?>: <?php echo $alldata['attributes']['invoiceCode']; ?></span>,
          <!-- <span class="order-status">Due Date # <?php //echo date('d-m-Y', strtotime($alldata['attributes']['dueDate'])); ?></span><br> -->
          <!-- <spanclass="base" style="font-size:16px;" ><?php //echo $alldata['attributes']['type']?></span><br><br> -->
          <span class="base" style="font-size:16px;"> <?php
          if(array_key_exists("poReference",$alldata['attributes'])){
            echo 'PO Code: '.$alldata['attributes']['poReference'];
          }else{
            echo '';
          }
           ?></span>


        <?php
      }
      // die;
       ?>
       
        </div>

    <ul class="items order-links"><li class="nav item current"><strong>Items</strong></li></ul><div class="order-details-items ordered">

        <div class="order-title">
            <strong>Items</strong>
        </div>

        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="my-orders-table" summary="Items Ordered">
                <caption class="table-caption">Items Ordered</caption>
                <thead>
                    <tr>
                        <th class="col name">Product Name</th>
                        <th class="col sku">SKU</th>
                        <th scope="col">Sale Price</th>
                        <th scope="col">Net Price</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Line Total</th>
                    </tr>
                </thead>
                <tbody>
                  <?php
                  $subtotal=0;
                  if(array_key_exists("details",$alldata['attributes'])){
                    $details=$alldata['attributes']['details'];

                    for($i=0;$i<count($details);$i++){

                      ?>
                    <tr>
                      <td><?php echo $details[$i]['description'];?></td>
                      <td><?php echo $details[$i]['itemName'];?> (<?php echo $details[$i]['um'];?>)</td>
                      <td><?php echo $currencycode.number_format((float)$details[$i]['sellPrice'], 2, '.', ',');?></td>
                      <td><?php echo $currencycode.number_format((float)$details[$i]['netSellPrice'], 2, '.', ',');?></td>
                      <td><?php echo $details[$i]['qty'];?> <?php echo $details[$i]['um'];?></td>
                      <td style="text-align:right"><?php echo $currencycode.number_format((float)$details[$i]['lineTotal'], 2, '.', ',');?></td>
                      </tr>
                    <?php
                  }
                  }else{

                  }


                ?>
                </tbody>

                <tfoot>
                  <?php
                  if(!empty($alldata)){
                    if(array_key_exists("details",$alldata['attributes'])){

                   ?>
                    <tr class="subtotal">
                        <th colspan="5" class="mark" scope="row">
                            Subtotal                    </th>
                        <td class="amount" data-th="Subtotal">
                            <span class="price"><?php echo $currencycode.number_format((float)$alldata['attributes']['subTotal'], 2, '.', ','); ?></span>                    </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="5" class="mark" scope="row">
                            Shipping &amp; Handling                    </th>
                        <td class="amount" data-th="Shipping &amp; Handling">
                            <span class="price"><?php echo $currencycode.number_format((float)$alldata['attributes']['freight'], 2, '.', ','); ?></span>                    </td>
                    </tr>
                    <tr class="shipping">
                        <th colspan="5" class="mark" scope="row">
                           VAT                   </th>
                        <td class="amount" data-th="Tax">
                            <span class="price"><?php echo $currencycode.number_format((float)$alldata['attributes']['tax'], 2, '.', ','); ?></span></td>
                    </tr>
                    <tr class="grand_total">
                        <th colspan="5" class="mark" scope="row">
                            <strong>Grand Total</strong>
                        </th>
                        <td class="amount" data-th="Grand Total">
                            <strong><span class="price"><?php echo $currencycode?><?php echo number_format((float)$alldata['attributes']['total'], 2, '.', ',');?></span></strong>
                        </td>
                    </tr>
                    <?php
                  }
                }
                     ?>
                </tfoot>
            </table>
        </div>
        <?php
  // echo "<pre>";
  // print_r($restInformation);
  // die;
  if(empty($alldata)){

  }else{
    if(array_key_exists("details",$alldata['attributes'])){
    ?>
        <div class="block block-order-details-view">
            <div class="block-title">
                <strong>Order Information</strong>
            </div>
            <div class="block-content">
                <div class="box box-order-shipping-address">
                    <strong class="box-title"><span>Shipping Address</span></strong>
                    <div class="box-content">
                      <?php
                      $addressShi=str_replace("\n","<br>",$alldata['attributes']['shipToNameAndAddress']);
                       ?>
                        <address><?php //echo $alldata['attributes']['shipToName']?>

                            <?php echo $addressShi?>


                        </address>
                    </div>
                </div>

                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span>Shipping Method</span>
                    </strong>
                    <div class="box-content">
                        <?php echo $alldata['attributes']['shippingMethod']?>                      </div>
                </div>

                <div class="box box-order-billing-address">
                    <strong class="box-title">
                        <span>Billing Address</span>
                    </strong>
                    <div class="box-content">
                      <?php
                      $address=str_replace("\n","<br>",$alldata['attributes']['billToNameAndAddres']);
                       ?>
                        <address><?php //echo $alldata['attributes']['billToName']?>

                            <?php echo $address?><br>


                        </address>
                    </div>
                </div>
                <div class="box box-order-billing-method">
                    <strong class="box-title">
                        <span>Payment Method</span>
                    </strong>
                    <div class="box-content">
                        <dl class="payment-method">
                            <dt class="title"><?php echo $alldata['attributes']['paymentMethodCode']?></dt>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
        <?php
      }
  }
?>

        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="http://127.0.0.1/magento224/index.php/sales/order/history/">
                    <span>Back to My Orders</span>
                </a>
            </div>
        </div>
    </div>

    <input name="form_key" type="hidden" value="NFKcfAdFfAWHxLAr"><div id="authenticationPopup" data-bind="scope:'authenticationPopup'">
        <script>
            window.authenticationPopup = {"autocomplete": "off", "customerRegisterUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/create\/", "customerForgotPasswordUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/forgotpassword\/", "baseUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/", "customerCheckoutUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/checkout\/#shipping"};
        </script>
        <!-- ko template: getTemplate() -->


        <!-- /ko -->

    </div>




</div>
<?php
} else{
?>
    <div class=""><div class="page-title-wrapper">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">Sorry something wrong order not found!!</span>    </h1>
        </div>
        <input name="form_key" type="hidden" value="NFKcfAdFfAWHxLAr"><div id="authenticationPopup" data-bind="scope:'authenticationPopup'">
        <script>
            window.authenticationPopup = {"autocomplete": "off", "customerRegisterUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/create\/", "customerForgotPasswordUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/customer\/account\/forgotpassword\/", "baseUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/", "customerCheckoutUrl": "http:\/\/127.0.0.1\/magento224\/index.php\/checkout\/#shipping"};
        </script>
        <!-- ko template: getTemplate() -->


        <!-- /ko -->

    </div>
    </div>
<?php } ?>
