<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="copyright_content">
        <div>
            <a href="https://www.facebook.com/LoveSandpiper" rel="external" target="_blank"><i class="link-facebook">&nbsp;</i></a>
            <a href="https://twitter.com/intent/follow?source=followbutton&variant=1.0&screen_name=sandpiper_shoes" rel="external" target="_blank"><i class="link-x">&nbsp;</i></a>
            <a href="https://www.youtube.com/@sandpipershoes" rel="external" target="_blank"><i class="link-youtube">&nbsp;</i></a>
            <a href="https://www.linkedin.com/company/sandpiper-shoes" rel="external" target="_blank"><i class="link-linkedin">&nbsp;</i></a>
            <a href="https://instagram.com/sandpipershoes?igshid=1az7a7ce7f989" rel="external" target="_blank"><i class="link-instagram">&nbsp;</i></a>
        </div>
        <span>
           <?= $block->escapeHtml($block->getCopyright()) ?>
        </span>
        <div class="copyright_content_createdby">
            Crafted with <i class="love"></i> by Rak Design</div>
    </div>
</small>
