<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Catalog\Helper\Product\Compare;
use Magento\CatalogWidget\Block\Product\ProductsList;
use Magento\Framework\App\Action\Action;
use Magento\Framework\Escaper;
use Magento\Wishlist\Helper\Data;

/** @var Escaper $escaper */
/** @var ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->count())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';
    $viewMode = 'grid';
    $imageDisplayArea = 'category_page_grid';

    $image = 'new_products_content_widget_grid';
    $_productCollection = $block->getProductCollection()->getItems();
    $_helper = $block->getData('outputHelper');

    $showWishlist = false;
    $showCompare = false;
    $showCart = false;
    $showAddToCart = false;
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    $showDescription = true;
    $pos = $block->getPositioned();
    ?>
    <div class="">
        <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
            <?php if ($block->getTitle()): ?>
                <div class="block-title">
                    <strong><?= $escaper->escapeHtml(__($block->getTitle())) ?></strong>
                </div>
            <?php endif ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
                        <div class="product-item-info"
                             id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                             data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= $escaper->escapeHtml($_product->getName()) ?>
                                    </a>
                                </strong>

                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_product->getShortDescription() ?>
                                    </div>
                                <?php endif; ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>

                                <?php if ($showAddToCart):?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif;?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">

                                        <?php if ($showAddToCart):?>
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()):?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form"
                                                          data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                          action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                          data-mage-init='{"catalogAddToCart": {}}'
                                                          method="post">
                                                        <?php $options = $block->getData('viewModel')->getOptionsData($_product); ?>
                                                        <?php foreach ($options as $optionItem): ?>
                                                            <input type="hidden"
                                                                   name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                                   value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                                        <?php endforeach; ?>
                                                        <input type="hidden"
                                                               name="product"
                                                               value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                        <input type="hidden"
                                                               name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                               value="<?=
                                                               /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                               ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                class="action tocart primary"
                                                                disabled>
                                                            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else:?>
                                                    <?php if ($_product->isAvailable()):?>
                                                        <div class="stock available">
                                                            <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else:?>
                                                        <div class="stock unavailable">
                                                            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <div class="actions-primary">
                                            <a href="<?= $escaper->escapeUrl($block->getProductUrl($_product)) ?>" class="action toproductview" title="<?= $block->escapeHtmlAttr(__('View Product')) ?>">
                                                <span><?= $escaper->escapeHtml(__('View Product')) ?></span>
                                            </a>
                                        </div>

                                        <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                            ) : '' ?>
                                        <div data-role="add-to-links" class="actions-secondary">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                        <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                            ) : '' ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= ($pos && strpos($pos, $viewMode . '-actions')) ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                            ) : '' ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif;?>
