<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Product\ReviewRenderer $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()): ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope
         itemtype="http://schema.org/AggregateRating">
        <?php if ($rating):?>
            <div class="rating-summary">
                <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
                <div class="rating-result"
                     id="rating-result_<?= $block->escapeHtmlAttr($block->getProduct()->getId()) ?>"
                     title="<?= $block->escapeHtmlAttr($rating) ?>%"
                >
                 <span>
                     <span>
                         <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?>
                         </span>% of <span itemprop="bestRating">100</span>
                     </span>
                 </span>
                </div>
            </div>
            <?= /* @noEscape */
            $secureRenderer->renderStyleAsTag(
                'width:' . $block->escapeHtmlAttr($rating) . '%',
                '#rating-result_' . $block->getProduct()->getId() . ' span'
            ) ?>
        <?php endif;?>
        <div class="reviews-actions">
            <span itemprop="reviewCount">(<?= $block->escapeHtml($block->getReviewsCount()) ?>)</span>&nbsp;
            <a id="read-review-product" class="action view" href="<?= $block->escapeUrl($url) ?>">
                <span><?= $block->escapeHtml(__('Read reviews')) ?></span>
            </a>
        </div>
    </div>
    <script type="text/javascript">
        require([
            "jquery",
        ],function($) {
            $("#read-review-product").click(function() {
                $('#product-info-tabs').accordion("activate", 2);
            });
        });
    </script>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $block->escapeUrl($urlForm) ?>">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
