<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
/** @var  Magento\ConfigurableProduct\Pricing\Price\ConfigurableRegularPriceInterface $regularPriceModel */
$regularPriceModel = $block->getPriceType('regular_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$isSaleCategory = $block->isProductList() && $this->helper(\Fyb\Theme\Helper\Product::class)->isSaleCategory();
$product = $regularPriceModel->getProduct();
$block->setData('is_vatexempt', $product->getIsVatexempt());

?>
<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>
    <div>
       <span class="old-price sly-old-price no-display">
            <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => '',
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]); ?>
        </span>
    </div>
<?php endif; ?>

<span class="normal-price">
    <?= /* @noEscape */
    $block->renderAmount($isSaleCategory ? $finalPriceModel->getAmount() : $regularPriceModel->getAmount(), [
//        'display_label' => $regularPriceModel->isChildProductsOfEqualPrices($product) ? '' : __('Starts from'),
        'display_label' => '',
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]);
    ?>
</span>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
