<div>
    <h2>Help & Advice</h2>
    <p>Looking for your local Sandpiper stockist? Would you like to order a free catalogue of our latest styles or get information on our delivery and returns policy? Click the links below. Still need assistance call free on 0800 822 3133 (Lines Open Mon-Fri 9am-4.45pm)</p>

    <div>
        <p>Find a Stockist</p>
        <p>Lorem ipsum dolor sit amet, odio consectetur adipiscing elit. </p>
        <a href="#">enter postcode</a>
    </div>
    <div>
        <p>Request a Catalogue</p>
        <p>Lorem ipsum dolor sit amet, odio consectetur adipiscing elit. </p>
        <a href="#">request</a>
    </div>
    <div>
        <p>Delivery and Returns</p>
        <p>Lorem ipsum dolor sit amet, odio consectetur adipiscing elit. </p>
        <a href="#">learn more</a>
    </div>
    <div>
        <p>Foot Measurement Guide</p>
        <p>Lorem ipsum dolor sit amet, odio consectetur adipiscing elit. </p>
        <a href="#">size guide</a>
    </div>
</div>
