<?php
/**
 * @author FYB Romania
 * @copyright Copyright (c) FYB Romania (https://fyb.ro)
 * @package Notification Bar for Magento 2
 */
/** @var $block \Fyb\NotificationBar\Block\Notification */
$minHeight = (int)$block->getConfig('min_height') > 0 ? (int)$block->getConfig('min_height'): 40;
$minHeightAdditional = (int)$block->getConfig('min_height', 'additional') > 0 ? (int)$block->getConfig('min_height', 'additional'): 40;
$stockistEnabled = $this->helper(\Fyb\StockistLocator\Helper\Data::class)->isEnabled();
$requestCatalogueEnabled = $this->helper(\Fyb\RequestCatalogue\Helper\Data::class)->isEnabled();
?>
<?php if ($block->needDisplay()): ?>
    <div class="sticky-notification-bar">
        <?php if ($block->getConfig('content', 'additional')): ?>
            <div class="sticky-additional"
                 style="background-color: <?php echo $this->getConfig('background_color', 'additional') ?>;
                     color: <?php echo $this->getConfig('text_color', 'additional') ?>;"
            >
                <div class="content-wrapper">
                    <div class="content" style="min-height: <?= $minHeight ?>px;">
                        <div class="promotion-top-content">
                            <?php echo $block->getConfig('content', 'additional') ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="sticky-general"
             style="background-color: <?php echo $this->getConfig('background_color') ?>;
                 color: <?php echo $this->getConfig('text_color') ?>;"
        >
            <div class="content-wrapper">
                <div class="content" style="min-height: <?= $minHeight ?>px;">
                    <div class="promotion-top-links">
                        <?php if ($stockistEnabled || $requestCatalogueEnabled): ?>
                            <?php if ($requestCatalogueEnabled): ?>
                                <a href="/request-catalogue"
                                   style="margin-right: 10px;"><?= __('Request a Catalogue') ?></a>
                            <?php endif; ?>
                            <?php if ($requestCatalogueEnabled): ?>
                                <a href="/stockist"><?= __('Find a Stockist') ?></a>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>


                    <div class="promotion-top-content">
                        <?php echo $block->getConfig('content') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        <?php echo $block->getConfig("custom_css")?>
    </style>

    <?php
    $isStickyGeneral = $block->getConfig('is_sticky');
    ?>
    <?php if ($isStickyGeneral): ?>
        <script>
        function makeStickyNotification(barType) {
            var notificationBar = document.getElementsByClassName("sticky-notification-bar")[0];
            notificationBar.style.position = "fixed";
            document.getElementsByClassName("page-header")[0].style.marginTop = notificationBar.offsetHeight + "px";
        }

        window.addEventListener("load", function () {
            window.addEventListener('resize', function(event) {
                makeStickyNotification();
            });
            makeStickyNotification();
        });
        </script>
    <?php endif; ?>
<?php endif; ?>
