<?php

ini_set('output_buffering', 'off');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use Magento\Framework\App\Bootstrap;
use Magento\Framework\App\Filesystem\DirectoryList;

$baseDir = dirname(__FILE__, 2);

require $baseDir . '/app/bootstrap.php';

$params = $_SERVER;
$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
    DirectoryList::PUB => [DirectoryList::URL_PATH => ''],
    DirectoryList::MEDIA => [DirectoryList::URL_PATH => 'media'],
    DirectoryList::STATIC_VIEW => [DirectoryList::URL_PATH => 'static'],
    DirectoryList::UPLOAD => [DirectoryList::URL_PATH => 'media/upload'],
];
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);

$obj = $bootstrap->getObjectManager();
$obj->get('\Magento\Framework\App\State')->setAreaCode(
    \Magento\Framework\App\Area::AREA_GLOBAL
); // for remove Area code is not set error
$storeManager = $obj->get('\Magento\Store\Model\StoreManagerInterface');
$categoryLinkManagement = $obj->get('\Magento\Catalog\Api\CategoryLinkManagementInterface');
$csvReader = $obj->get('\Magento\Framework\File\Csv');
$categoryCollection = $obj->create(\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory::class);
$productRepository = $obj->get('Magento\Catalog\Model\ProductRepository');
$urlRewriteFactory = $obj->get('\Magento\UrlRewrite\Model\UrlRewriteFactory');

$productsData = $csvReader->getData($baseDir . '/scripts/csv/Urls.csv');
$header = $productsData[0];
unset($productsData[0]);

$existingCategories = [];


foreach ($productsData as $row) {
    $productData = array_combine($header, $row);

    try {
        $product = $productRepository->get($productData['sku']);
    } catch (\Exception) {
        continue;
    }

    if ($product->getTypeId() == 'simple') {
        continue;
    }

    $urlKey = trim($productData['request_path']);
    $initialUrl = $product->getUrlKey() . '.html';

    if ($initialUrl == $urlKey) {
        continue;
    }

    try {
        /** @var \Magento\UrlRewrite\Model\UrlRewrite $urlRewriteModel */
        $urlRewriteModel = $urlRewriteFactory->create();
        /* set current store id */
        $urlRewriteModel->setStoreId(1);
        $urlRewriteModel->setEntityType('product');
        $urlRewriteModel->setEntityId($product->getId());
        $urlRewriteModel->setRequestPath($urlKey);
    $urlRewriteModel->setTargetPath($initialUrl);
//        $urlRewriteModel->setTargetPath('catalog/product/view/id/' . $product->getId());

        $urlRewriteModel->setIsSystem(0);
        $urlRewriteModel->setIsAutogenerated(0);
        $urlRewriteModel->setRedirectType(301);

        $urlRewriteModel->save();
//        print_r([$urlRewriteModel->getData()]);
//        exit;
    } catch (\Exception $e) {

    }
}

