<?php
/**
 * @package     Plumrocket_ProductFilter
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>

<?php /** @var \Magento\LayeredNavigation\Block\Navigation $block */ ?>

<?php if ($block->canShowBlock()): ?>
    <?php
    $active = [0];
    $i = 0;
    $activeFilters = $block->getRequest()->getParams();

    foreach ($block->getFilters() as $code => $filter) {
        if ($i != 0 && isset($activeFilters[$filter->getData('pf_attribute_code')])) {
            $active[] = $i;
        }
        $i++;
    }

    $accordionSettings = json_encode([
        'openedState'         => 'active',
        'collapsible'         => true,
        'active'              => $active, // Opened by default
        'multipleCollapsible' => true
    ]);
    ?>

    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @noEscape */ $filtered ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Shop By')) ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a id="product-filter-clear"
                       data-pr-filter="clearAll"
                       href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                       class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear all filters')) ?></span>
                    </a>
                </div>
            <?php endif; ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $code => $filter): ?>
                <?php if ($code === 'price' || $filter->getItemsCount()): ?>
                    <?php if (! $wrapOptions): ?>
                        <?php $wrapOptions = true;?>
                        <div class="filter-options"
                             id="narrow-by-list"
                             data-role="content"
                             data-mage-init='{"accordion":<?= /* @noEscape */ $accordionSettings ?>}'>
                    <?php endif; ?>

                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title">
                            <?= $block->escapeHtml(__($filter->getName())) ?>
                        </div>
                        <div data-role="content" class="filter-options-content">
                            <?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    (function (){
                        var filterBlock = document.getElementById('layered-filter-block');
                        if (filterBlock) {
                            filterBlock.classList.add('filter-no-options');
                        }
                    })();
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
