<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>


<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" id="product-info-tabs" data-mage-init='{
        "accordion":{
            "active": [],
            "collapsible": true,
            "openedState": "active",
            "openOnFocus": false,
            "multipleCollapsible": true
        }}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!$html || !trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <div id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" data-role="trigger" class="product_details_tab_title">
                        <?= /* @noEscape */ $label ?>
                    </div>
                </div>

                <div id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content"  class="product_details_tab_content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
