<button type="button" id="size-guide-button" class="secondary">
    <span><?= $block->escapeHtml(__('Size Guide')) ?></span>
</button>

<div id="modal-size-guide" style="display:none;">
    <div class="modal-body-content">
        <?= $block->getChildHtml('product.info.sizes.chart') ?>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal-size-guide'));
        $("#size-guide-button").click(function() {
            $('#modal-size-guide').modal('openModal');
        });
    });
</script>
