<?php
/**
* @var $block \Magento\Catalog\Block\Product\View
*/

use Magento\Store\Model\ScopeInterface;

$_product = $block->getProduct();
$vatHelper = $this->helper(\Meetanshi\VatExempt\Helper\Data::class);
?>

<?php if ($vatHelper->isEnabled()): ?>
    <div class="detail-vat-exemption">
        <?php if ($_product->getData('is_vatexempt')=='1'): ?>
            <div>
                <span>VAT RELIEF AVAILABLE</span>
                <button id="at-relief-toolti" class="vat-relief-tooltip">?</button>
            </div>

        <?php endif; ?>
    </div>
    <div id="modal-vat-relief" style="display:none;">
        <div class="modal-body-content">
            <?= $block->getChildHtml('product.info.vat.tooltip') ?>
        </div>
    </div>


    <script type="text/javascript">
        require([
            "jquery",
            "Magento_Ui/js/modal/modal"
        ],function($, modal) {

            var options = {
                type: 'popup',
                responsive: true,
                buttons: []
            };

            var popup = modal(options, $('#modal-vat-relief'));
            $("#at-relief-toolti").click(function() {
                $('#modal-vat-relief').modal('openModal');
            });
        });
    </script>
<?php endif; ?>
