<?php
$viewModel = $block->getData('view_model');
$block = $viewModel->getBanner($block);
?>
<?php if (!empty($block->getData('banner'))): ?>
    <?php $styleVar ='';
    if ($viewModel->getConfig('sparsh_banner/advance/left_padding') !='') {
        $styleVar .= "padding-left :".$viewModel->getConfig('sparsh_banner/advance/left_padding').";";
    }  ?>
    <?php if ($viewModel->getConfig('sparsh_banner/advance/right_padding') !='') {
        $styleVar .= "padding-right :".$viewModel->getConfig('sparsh_banner/advance/right_padding').";";
    }  ?>
    <div class="sparsh_banner" style="<?php echo $styleVar; ?>"  >
        <style>
            .sparsh_banner_slider{
                display: none;
            }
            .slick-initialized.sparsh_banner_slider{
                display: block;
            }
        </style>
        <div class="sparsh_banner_slider">
            <?php  foreach ($block->getData('banner') as $banner): ?>
                <div>
                    <?php if ($banner->getBannerType() == "Video"):?>
                        <div class="video-thumb">
                            <video
                                    controls
                                <?= $banner->getBannerVideoThumbImage() ? "poster='" . $viewModel->getMediaPath().$banner->getBannerVideoThumbImage() . "'" : '' ?>
                                <?= $banner->getBannerVideoAutoplay() ? "autoplay" : "" ?>
                                    muted
                                    loop>
                                <source src="<?= $escaper->escapeHtml($viewModel->getMediaPath().$banner->getBannerVideo()) ?>" type="video/mp4">
                            </video>
                        </div>
                    <?php endif;?>

                    <?php if ($banner->getBannerType() == "Youtube"):?>
                        <div class="youtube-thumb">
                            <iframe src="https://www.youtube.com/embed/<?= $escaper->escapeUrl($banner->getBannerYoutube()) ?>?controls=0&rel=0<?php if ($banner->getBannerVideoAutoplay()) { echo "&autoplay=1";
                            } else { echo "&autoplay=0"; } ?>&modestbranding=1&disablekb=1"
                                <?php if ($banner->getBannerVideoAutoplay()) { echo "allow='autoplay;'"; } ?> frameborder="0" allowfullscreen>
                            </iframe>
                        </div>
                    <?php endif;?>
                    <?php if ($banner->getBannerType() == "Vimeo"):?>
                        <iframe src="https://player.vimeo.com/video/<?= $escaper->escapeUrl($banner->getBannerVimeo()) ?>?&byline=0"  frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                        <div class="vimeo-wrapper">

                        </div>
                    <?php endif;?>
                    <?php if ($banner->getBannerType() == "Image"):?>
                        <?php if ($banner->getLabelButtonText() == "" && $banner->getCallToAction() != ""): ?><a href="<?= $escaper->escapeHtml(($banner->getCallToAction()?$banner->getCallToAction():'#')) ?>" class="btn btn-md btn-banner" target="_blank"><?php endif;?>
                        <div class="image-thumb">
                            <img src="<?= $escaper->escapeHtml($viewModel->getMediaPath().$banner->getBannerImage()) ?>" alt="<?= /* @noEscape */ ($banner->getBannerTitle()?$banner->getBannerTitle():"Sparsh Banner");?>">
                        </div>
                        <?php if ($banner->getBannerDescription() != "" || $banner->getBannerTitle() != ""):?>
                            <div class="caption">
                                <div class="title">
                                    <div class="container">
                                        <?php if ($banner->getBannerTitle() != ""):?>
                                            <h2><?= $escaper->escapeHtml($banner->getBannerTitle()) ?></h2>
                                        <?php endif; ?>
                                        <?php if ($banner->getBannerDescription() != ""):?>
                                            <?= /* @noEscape */ $viewModel->getCmsFilterContent($banner->getBannerDescription()) ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($banner->getLabelButtonText() != ""): ?>
                                    <div class="container">
                                        <a href="<?= $escaper->escapeHtml(($banner->getCallToAction()?$banner->getCallToAction():'#')) ?>" class="btn btn-md btn-banner" target="_blank">
                                            <?= $escaper->escapeHtml($banner->getLabelButtonText()) ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif;?>
                        <?php if ($banner->getLabelButtonText() == "" && $banner->getCallToAction() != ""): ?></a><?php endif;?>
                    <?php endif;?>
                </div>
            <?php endforeach;  ?>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Sparsh_Banner/js/banner-slider": {
                    "autoplay": "<?= /* @noEscape */ $viewModel->getConfig('sparsh_banner/advance/auto_rotation'); ?>",
            "autoplay_speed": "<?= /* @noEscape */ $viewModel->getConfig('sparsh_banner/advance/auto_rotation_speed'); ?>"
        }
    }
}
    </script>
<?php endif; ?>
